### ISSUE TITLE
Cannot create db

### ISSUE THREAD

**Issue by monolifed** [RyuzakiKK/NoteCrypt#1]
I cannot create db file. I tried creating with initial settings, selecting with ghostcommander and inputting manually. Nothing worked

**Comment by RyuzakiKK** [comment]
I need more information for understand your problem. Can you answer to the following questions?
1) Which Android version are you using?
2) If you are on Android 6.0+, did you grant NoteCrypt the 'storage'  permission?
3) If you open NoteCrypt and in the field "Enter database filename:" you write SecretNotes.ncf, then press the button "Create" and choose a password what happens?
4) Can you provide the steps to reproduce your problem?

Thanks

**Comment by monolifed** [comment]
1. 4.1.2
2. no
3. Error creating db. Check the correctness of the path
4. (3) and the ones I mentioned above

maybe not supported by 4.1.2?

**Comment by RyuzakiKK** [comment]
With the last commit I fixed this issue.
It was caused by an exception of the PRNGfixes.
Soon I'll push an update of NoteCrypt.

**Comment by monolifed** [comment]
Yes it works

**Comment by RyuzakiKK** [comment]
Perfect!
