### ISSUE TITLE
NoteCrypt crashes when trying to save/return to previous screen on Lineage15.1 (8.1 base)

### ISSUE THREAD

**Issue by ghost** [RyuzakiKK/NoteCrypt#11]
The tool crashes when trying to either save the database or when trying to navigate inside it.

This behavior hasn't existed on Lineage14.1 which bases on AOSP 7's code, also did I triple check for missing read/write permissions but no dice.

That said, to edit any entry is impossible by now, however, reading entries work when considering that returning a page will make the tool crash.

**Comment by RyuzakiKK** [comment]
Can you please test it with a fresh new database? From the home page create a new db (with a different name) and check if there is the same problem.

In this way I'll know if I can reproduce the bug or if it's only your db that is in an inconsistent state.

**Comment by ghost** [comment]
> 
> 
> Can you please test it with a fresh new database? From the home page create a new db (with a different name) and check if there is the same problem.
> 
> In this way I'll know if I can reproduce the bug or if it's only your db that is in an inconsistent state.

Thanks for the quick reply.

Indeed, this behavior also occurs for me with a new database placed onto the phone's internal storage and the same password.

**Comment by RyuzakiKK** [comment]
Ok maybe this is a good news then, thank for this bug report.

As soon as I have some free time I'll install the last version of Lineage and I'll try to trace the problem.

**Comment by ghost** [comment]
That's great to read.
Hopefully it's fixable and not some unique bug related to the port of Lineage15.1 for my device :smiley:

**Comment by RyuzakiKK** [comment]
I just tried with a vanilla Android 8.1 and I was unable to reproduce it.
I'm quite busy in this period so probably I'll not be able to test it with Lineage before the beginning of next month.

I'll report back once I do.

**Comment by RyuzakiKK** [comment]
I tried the latest build of Lineage 15.1 in a Oneplus one and no crashes happened.

@floatingCactus If you want to help me figuring out what's the problem, let NoteCrypt crash again and then post its log.
https://f-droid.org/en/docs/Getting_logcat_messages_after_crash/
