### ISSUE TITLE
Provide new translations

### ISSUE THREAD

**Issue by RyuzakiKK** [RyuzakiKK/NoteCrypt#13]
Thanks to all your good contributions right now NoteCrypt is available in English, Italian, Japanese, Brazilian Portuguese, Portuguese, German, Lithuanian, Hungarian, Romanian, Egyptian Arabic, Ukrainian, Greek, French, Kazakh and Russsian.
More languages would be appreciated.

The strings to translate are about 80 and can be found here https://github.com/RyuzakiKK/NoteCrypt/blob/master/app/src/main/res/values/strings.xml

The new translations needs to be placed inside a new folder called values-xx-rXX  under `/app/src/main/res/` where the first xx is the code of the language, and the other XX is the country code. If in doubt just ask.

**Comment by msdeibel** [comment]
I'll take care of the translation to German.

**Comment by RyuzakiKK** [comment]
Now thanks to @Trol1337 we also have a Lithuanian translation.

**Comment by alejandrocq** [comment]
I'm going to do the translation to Spanish :)

**Comment by AhmedEzzat12** [comment]
does it handles RTL languages like Arabic ? if so i can take care of translating it to arabic.

**Comment by RyuzakiKK** [comment]
@Zod101 Yeah it should handle RTL. Thanks.

**Comment by nikgil** [comment]
I can do Russian if (surprisingly) no one has done it yet.

**Comment by yeliztaneroglu** [comment]
I'm going to do the translation to Turkish :)

**Comment by RyuzakiKK** [comment]
@msdeibel I'd like to inform you that another user just did the German translation #15

**Comment by NayakNavin** [comment]
I'll translate to Hindi.

**Comment by alsoknownasdrew** [comment]
I can provide Russian translation

**Comment by nikmanG** [comment]
> 
> 
> I can provide Russian translation

already doing it.

**Comment by RyuzakiKK** [comment]
@nikmanG I'm sorry but he already did a PR for the Russian translation.
Once I merge it you are welcome to double check his translation, and if there are any issues/typo you can fix them.

**Comment by zandraaperjesi** [comment]
I will do a Hungarian translation

**Comment by lopno** [comment]
I wil do Danish translations.

**Comment by xp0** [comment]
Created a PR for Romanian translation.

**Comment by RyuzakiKK** [comment]
Thank you @xp0, already merged.

**Comment by gwenu** [comment]
I'll do Ukrainian translation.

**Comment by galloj** [comment]
I will do Czech translation.

**Comment by marcosstefani** [comment]
I will do Portuguese Translation.

**Comment by yirrilo** [comment]
Hi, I'll take care of the translation to French.

**Comment by infiniteoverflow** [comment]
i can help you to do it in Hindi

**Comment by Tititesouris** [comment]
I have improved the French translations with PR #28

**Comment by jwojciec** [comment]
Hi, I'll open PR with translation to Polish.

**Comment by dennybiasiolli** [comment]
I'll help you with Italian

**Comment by RyuzakiKK** [comment]
@dennybiasiolli Thanks but Italian is already done (I'm Italian too)

**Comment by dennybiasiolli** [comment]
@RyuzakiKK sorry, I didn't look inside the sources until I cloned the repository :sweat_smile:

**Comment by troyodk** [comment]
I will take Spanish MX

**Comment by wolframtheta** [comment]
I will help you with Catalan translation

**Comment by wonrax** [comment]
I'm translating this to Vietnamese

**Comment by pleum** [comment]
I will do a Thai translation

**Comment by mahewi** [comment]
I can add Finnish translation

**Comment by kitwtnb** [comment]
I will translate to Japanese.
I'm a little not good in English, so can I translate only a part?

**Comment by RyuzakiKK** [comment]
Thanks @kitwtnb but the Japanese translation is already available.

**Comment by jovanzers** [comment]
#48 Add Indonesian translation

**Comment by RyuzakiKK** [comment]
Version 1.44 with all these new translations is now up on Google Play and, very soon, on F-Droid.
Thank you all.
