### ISSUE TITLE
Recent list

### ISSUE THREAD

**Issue by monolifed** [RyuzakiKK/NoteCrypt#4]
Can you add an option to delete them or an option to not save them at all?

**Comment by RyuzakiKK** [comment]
Currently if you long press a database entry it will let you delete it.
But keep in mind that if the database exist in the filesystem, not only the entry from the list will be removed, but also the database itself.

Is this behaviour good enough?

**Comment by monolifed** [comment]
I think it would be nicer if it gave another option to forget without deleting the database itself.
Maybe It shouldn't forget the database in the default folder though.
