### ISSUE TITLE
Crashes if I take too long/maybe autosave?

### ISSUE THREAD

**Issue by 5731la** [RyuzakiKK/NoteCrypt#52]
I have to type in a different editor and then copy it over because of this

**Comment by RyuzakiKK** [comment]
I tried to keep the note edit page open for about 40 minutes and I was unable to reproduce the crash.
Are you able to reliably reproduce this bug? If so, what are the exact steps?

**Comment by RyuzakiKK** [comment]
I'm closing this but feel free to report back if it is still happening
